# -*- coding: utf-8 -*-
"""MeBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLJixYXay-k9NC3IQJVic1FUd0-pt4Z3
"""

!pip install transformers datasets
!pip install accelerate

from google.colab import files
uploaded = files.upload()

from datasets import Dataset
import pandas as pd

# Read and split into chunks
with open("cleaned_chat.txt", "r", encoding="utf-8") as f:
    data = f.read().strip().split("\n\n")

# Convert to dataset
df = pd.DataFrame(data, columns=["text"])
dataset = Dataset.from_pandas(df)

from transformers import GPT2Tokenizer, GPT2LMHeadModel, DataCollatorForLanguageModeling, TrainingArguments, Trainer

model_name = "distilgpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token  # to avoid padding issues
model = GPT2LMHeadModel.from_pretrained(model_name)

# Tokenize data
def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

tokenized_dataset = dataset.map(tokenize, batched=True)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

from transformers import TrainingArguments

# training_args = TrainingArguments(
#     output_dir="./mebot-model",
#     overwrite_output_dir=True,
#     per_device_train_batch_size=2,
#     num_train_epochs=3,
#     save_steps=500,
#     save_total_limit=1,
#     logging_steps=100,
#     fp16=False,
#     report_to="none",
# )


training_args = TrainingArguments(
    output_dir="./mebot-model",
    per_device_train_batch_size=4,
    num_train_epochs=1,
    save_steps=10_000,
    save_total_limit=1,
    logging_steps=5,
    fp16=False,
    report_to="none",
)


# trainer = Trainer(
#     model=model,
#     args=training_args,
#     data_collator=data_collator,
#     train_dataset=tokenized_dataset,
# )


# Limit dataset for trial run
tokenized_dataset = tokenized_dataset.select(range(50))

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=tokenized_dataset,
)

trainer.train()

trainer.save_model("./mebot-model")
tokenizer.save_pretrained("./mebot-model")

# Zip the model for download
!zip -r mebot-model.zip ./mebot-model

# Download the zip
from google.colab import files
files.download("mebot-model.zip")

from transformers import pipeline, GPT2LMHeadModel, GPT2Tokenizer

# Load the trained model
model_path = "./mebot-model"
tokenizer = GPT2Tokenizer.from_pretrained(model_path)
model = GPT2LMHeadModel.from_pretrained(model_path)

# Create a text generation pipeline
chatbot = pipeline("text-generation", model=model, tokenizer=tokenizer)

# Try it with a prompt
prompt = "Friend: what's your plan for today?\nYou:"
output = chatbot(prompt, max_length=100, num_return_sequences=1, pad_token_id=tokenizer.eos_token_id)

print(output[0]['generated_text'])

import re
from transformers import pipeline, GPT2LMHeadModel, GPT2Tokenizer

# Load the trained model
model_path = "./mebot-model"
tokenizer = GPT2Tokenizer.from_pretrained(model_path)
model = GPT2LMHeadModel.from_pretrained(model_path)

# Create a text generation pipeline
chatbot = pipeline("text-generation", model=model, tokenizer=tokenizer)

# Function to clean and format the bot's reply
def clean_reply(raw_output):
    # Extract reply after "You:"
    reply = raw_output.split("You:")[-1].split("Friend:")[0].strip()

    # Limit repeated emojis to 2 max
    reply = re.sub(
        r'([\U0001F600-\U0001F64F\U0001F300-\U0001F6FF\U0001F1E0-\U0001F1FF])\1{2,}',
        r'\1\1',
        reply
    )

    # Stop at first full stop or newline
    reply = re.split(r'[\n.!?]', reply)[0].strip()

    return reply


# Example prompt
prompt = "Friend:what's new?\nYou:"

# Generate a response
output = chatbot(
    prompt,
    max_length=50,
    num_return_sequences=1,
    pad_token_id=tokenizer.eos_token_id,
    temperature=0.9,
    top_p=0.95,
    repetition_penalty=1.2
)

raw = output[0]['generated_text']

# Clean the generated reply
reply = clean_reply(raw)

# Print the cleaned reply
print("You:", reply)

